version: '3.1'

services: 





    whoami:
        container_name: whoami
        image: containous/whoami:latest

    mysql:
        image: mysql:latest
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootPassword
            MYSQL_DATABASE: huginn
            MYSQL_USER: user
            MYSQL_PASSWORD: password

            
    huginn:
        image: huginn/huginn:latest
        container_name: huginn

  db:
     image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
       environment:
        MYSQL_ROOT_PASSWORD: example

 adminer:
        image: adminer
        restart: always
        ports:
     - 8080:8080
